# .github/workflows/ci_train.yml

name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run main file
        run: |
          python main.py

      - name: Setup CML
        uses: iterative/setup-cml@v2

      - name: Run tests
        run: |
          python -m unittest discover

      - name: Create CML Report 
        env:
          REPO_TOKEN: ${{secrets.CI_TRAIN}}
        run: |
          echo "# First Line of our report" >> report.md
          echo "## Bar Plots" >> report.md
          echo '![](./bars.png "Bar plot")' >> report.md
          echo '![](./lines.png "Lines plot")' >> report.md

          cml comment create report.md


